app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.homepage.views import IndexView
from core.login.views import *
from django.conf.urls import handler400
from core.erp.views.dashboard.views import page_not_found404


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('erp/', include('core.erp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views.producto.views import *
from core.erp.views.dashboard.views import *

app_name = 'app'

urlpatterns = [
    # PADRON
    # path('list/', prueba),
    path('producto/list/', ProductoListView.as_view(), name='producto_list'),
    path('producto/create/', ProductoCreateView.as_view(), name='producto_create'),
    path('producto/update/<int:pk>/', ProductoUpdateView.as_view(), name='producto_update'),

    # PANEL DASHBOARD
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

]

app/core/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.login.views import *

app_name = 'access'

urlpatterns = [
    # category
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('reset/password/', ResetPasswordView.as_view(), name='reset-password'),
    # path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change-password')
]

app/core/user/urls.py
from django.urls import path

from core.user.views import *

app_name = 'user'

urlpatterns = [
    # USER
    path('list/', UserListView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    # path('profile/', UserProfileView.as_view(), name='user-profile'),
    # path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

app/core/erp/views/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.shortcuts import render


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    # @method_decorator(csrf_exempt)
    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request, *args, **kwargs)
    #
    # def get(self, request, *args, **kwargs):
    #     request.user.get_group_session()
    #     return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# Paginas de ERRORES
def page_not_found404(request, exception):
    return render(request,'404.html')

app/templates/body.html
{% extends 'home.html' %}

{% load static %}

<!-- Body -->
{% block body %}
    <body class="hold-transition sidebar-mini sidebar-collapse layout-footer-fixed">
    <div class="wrapper">

        {% include 'navbar.html' %}

        {% include 'sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            {% include 'contentheader.html' %}

            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">

                            <div class="card">

                                {% block data_body %}

                                {% endblock %}

                            </div>

                        </div>
                    </div>
                </div>
            </section>

        </div>

        {% include 'footer.html' %}

    </div>
    <!-- JavaScript -->
    {% block javascript %}

    {% endblock %}
    <!-- ./JavaScript -->
    <!-- Mensaje ERROR Permisos -->
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>

    </body>
{% endblock %}
<!-- ./Body -->

app/templates/contentheader.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="userColor">Bienvenido <strong>{{ request.user.username }}</strong></h1>
{#                <h1>Bienvenido <strong>{{ request.user.get_full_name }}</strong></h1>#}
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-decoration-none color-icons" href="{% url 'app:producto_list' %}"><i class="fa-solid fa-computer"></i> Producto</a></li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- /.content-header -->

app/templates/create.html
{% extends 'body.html' %}

{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}

{% block head_extra %}
    {% block head_form %}

    {% endblock %}
{% endblock %}

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." id="FormCreate" enctype="multipart/form-data">
        <div class="card-header card-primary card-outline">
            <h3 class="card-title">
                {% if action == 'add' %}
                    <i class="fa-solid fa-plus"></i>
                {% else %}
                    <i class="fa-solid fa-rotate"></i>
                {% endif %}
                {{ title }}
            </h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- ./Card Header -->
        <!-- Card Body -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i> ! Ha ocurrido un ERROR !</h5>
                    <ul>
                        {% for field in form %}
                            {% for error in form %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% for field in form.visible_fields %}
                <label for="name">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
            {% endfor %}
        </div>
        <!-- ./Card Body -->
        <!-- Card Footer-Buttons -->
        <div class="card-footer text-center">
            {% if action == 'add' %}
                <button type="submit" style="background-color:var(--blue02); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-plus"></i> Crear
                </button>
                <button type="button" onclick="limpiarForm()" style="background-color:var(--orange01); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-trash-can"></i> Limpar
                </button>
            {% else %}
                <button type="submit" id="upDates" style="background-color:var(--green05); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-rotate"></i> Actualizar
                </button>
            {% endif %}
            <a href="{{ list_url }}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark"></i> Cancelar
            </a>
        </div>
        <!-- ./Card Footer-Buttons -->
    </form>

    <script>
        function limpiarForm() {
            document.getElementById("FormCreate").reset();
        }

        $('form').on('submit', function (e) {
            e.preventDefault();
            let dataForm = new FormData(this);
            alert_confirm(window.location.pathname, dataForm, 'Confirmar', '¿Estás seguro de realizar la siguiente Acción?', function () {
                location.href = '{{ list_url }}';
            });
        });

    </script>

{% endblock %}
<!-- ./Data Body -->

app/templates/dashboard.html
{% extends "body.html" %}

{% load static %}

{% block head_extra %}
    <style>
        img {
            max-width: 100%;
            display: block;
            width: 60%;
            margin: auto;
        }
    </style>

{% endblock %}


{% block data_body %}

    <sec class="card-body dashboard-card-body">
        <div class="hero-img">
            <img src="{% static 'image/07-img.png' %}" alt="">
        </div>

    </sec>
    <!-- Footer-Buttons -->
    {% block footer_buttons %}

    {% endblock %}
    <!-- ./Footer-Buttons -->

{% endblock %}

app/templates/delete.html
{% extends 'body.html' %}

{% load static %}

{% load widget_tweaks %}

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." enctype="multipart/form-data">

        <div class="card card-danger card-outline">
            <div class="card-header">
                <h3 class="card-title" style="color:var(--red02);">
                    <i class="fas fa-solid fa-trash-can"></i>
                    {{ title }}
                </h3>
            </div>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i>
                        ¡Ha ocurrido un ERROR al intentar Eliminar el registro!
                    </h5>
                </div>
            {% endif %}
            <div class="alert text-white" style="background-color:var(--red02);">
                <h5><strong><i class="fa-solid fa-triangle-exclamation"></i> Notificación!</strong></h5>
                ¿Estás seguro de eliminar el registro: <strong> {{ object.id }} </strong>? Si confirma la eliminación,
                no podrá acceder nuevamente a este Registro nuevamente.
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" style="background-color:var(--red02); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded">
                <i class="fa-solid fa-trash-can sm-1"></i> Confirmar
            </button>
            <a href="{{ list_url }}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark ml-1"></i> Cancelar
            </a>
        </div>
    </form>

    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            let parameters = new FormData(this);
            alert_confirm(window.location.pathname, parameters, 'Notificación', '¿Estas seguro de Eliminar el siguiente Registro?', function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro Eliminado con Éxito',
                    icon: 'success',
                    timer: 2000,
                    onClose: () => {
                        location.href = '{{ list_url }}';
                    }
                }).then((result) => {

                });
            });
        });
    </script>

{% endblock %}
<!-- ./Data Body -->


{#$('form').on('submit', function (e) {#}
{#            e.preventDefault();#}
{#            $.ajax({#}
{#                url: window.location.pathname,#}
{#                type: 'POST',#}
{#                data: {},#}
{#                datatype: 'json'#}
{#            }).done(function (data) {#}
{#                if (!data.hasOwnProperty('error')) {#}
{#                    location.href = '{{ list_url }}';#}
{#                    return false;#}
{#                }#}
{#                message_error(data.error);#}
{#            }).fail(function (jqXHR, textStatus, errorThrawn) {#}
{#                alert(textStatus + ' - ' + errorThrawn);#}
{#            }).always(function (data) {#}
{##}
{#            });#}
{#        });#}

app/templates/footer.html
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        <strong> | 2023 - 2023 | </strong>
    </div>
    <!-- Default to the left -->
    <strong> Aplicación Técnica <a href="#"></a></strong>
</footer>

app/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:,">
    <title>{{ title }}</title>
    <!-- Bootstrap -->
    <link href="{% static 'librery/bootstrap-5.3.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'librery/bootstrap-5.3.0/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'librery/bootstrap-5.3.0/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'librery/bootstrap-5.3.0/js/popper.min.js' %}"></script>
    <!-- ./Bootstrap -->
    <!-- AdminLTE3 -->
{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">#}
    <link rel="stylesheet" href="{% static 'librery/AdminLTE-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'librery/AdminLTE-3.2.0/dist/css/adminlte.min.css' %}">
    <script src="{% static 'librery/AdminLTE-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'librery/AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'librery/AdminLTE-3.2.0/dist/js/adminlte.min.js' %}"></script>
    <!-- ./AdminLTE3 -->
    <!-- Fontawesome -->
    {#    <script src="https://kit.fontawesome.com/606bbbad74.js" crossorigin="anonymous"></script>#}
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/fontawesome.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/solid.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/brands.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/all.min.js' %}"></script>
    <!-- ./Fontawesome -->
    <!-- Font Google -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <!-- ./Font Google -->
    <!-- Sweetalert2 -->
    <script src="{% static 'librery/sweetalert2/sweetalert2.min.css' %}"></script>
    <script src="{% static 'librery/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'librery/sweetalert2/sweetalert2.min.js' %}"></script>
    <!-- ./Sweetalert2 -->
    <!-- Jquery-Confirm (Alert) -->
    <link rel="stylesheet" href="{% static 'librery/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'librery/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Jquery-Confirm (Alert) -->
    <!-- My CSS & Functions -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- ./My CSS & Functions -->
    <!-- Extra Head -->
    {% block head_extra %}

    {% endblock %}
    <!-- ./Extra Head -->
</head>

<!-- Body -->
{% block body %}

{% endblock %}
<!-- ./Body -->

</html>

app/templates/list.html
{% extends 'body.html' %}

{% load static %}
<!-- Extra Librerys -->
{% block head_extra %}
    <link rel="stylesheet" href="{% static 'librery/datatables-1.10.22/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'librery/datatables-1.10.22/plugins/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'librery/datatables-1.10.22/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/js/responsive.bootstrap4.min.js' %}"></script>
    <!-- Head List -->
    {% block head_List %}

    {% endblock %}
    <!-- ./Head List -->

{% endblock %}
<!-- ./Extra Librerys -->

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <div class="card-header card-color card-outline">
        <h3 class="card-title"><i class="fa-solid fa-list-ul"></i> {{ title }}</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
        </div>
    </div>
    <!-- ./Card Header -->
    <!-- Table -->
    <div class="card-body">
        <table id="data" class="table table-striped table-hover table-sm">
            <thead style="background-color:var(--blue01);" class="text-white">
            {% block columns %}

            {% endblock %}
            </thead>
            <tbody>
            {% block rows %}

            {% endblock %}
            </tbody>
        </table>
    </div>
    <!-- ./Table -->
    <!-- Footer-Buttons -->
    {% block footer_buttons %}

    {% endblock %}
    <!-- ./Footer-Buttons -->

{% endblock %}
<!-- ./Data Body -->
<!-- JavaScript -->
{% block javascript %}

{% endblock %}
<!-- ./JavaScript -->

app/templates/navbar.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            {#            <a href="../../index3.html" class="nav-link">Home</a>#}
            <a href="" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa-solid fa-microchip"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fa-solid fa-computer"></i> Producto
                </a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa-solid fa-user-gear"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header" style="font-size: 12px;">
                            Su último acceso fue {{ request.user.last_login }}
                        </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa-solid fa-user-pen mr-2"></i> Editar Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa-solid fa-user-lock mr-2"></i> Cambiar Password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>El sistema está preparado para realizar diferentes acciones</p>
                </a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'access:logout' %}">
                <i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>

    </ul>
</nav>
<!-- /.navbar -->

app/templates/sidebar.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4 text-white">
    <!-- Brand Logo -->
    <a href="{% url 'app:dashboard' %}" class="brand-link">
        {#  <a href="../../index3.html" class="brand-link">#}
        <img src="{% static 'image/logo.png' %}" alt="Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8; background-color:var(--white01)">
        {#    <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">#}
        <span class="brand-text font-weight-light"></span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                {#                <img src="#" class="img-circle elevation-2" alt="User Image">#}
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
{#                            <img src="../../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">#}
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview"
                role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                      <i class="nav-icon fas fa-solid fa-microchip"></i><p> Producto <i class="right fa-solid fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                          <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa-solid fa-computer"></i>
                                <p> Producto</p>
                            </a>
                          </li>
                          <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa-solid fa-computer"></i>
                                <p> Producto</p>
                            </a>
                          </li>
                    </ul>
                </li>

            </ul>

            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                      <i class="nav-icon fa-solid fa-user-group"></i><p> Usuarios </p>
                    </a>
                </li>

            </ul>

            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="{% url 'access:logout' %}" class="nav-link">
                      <i class="nav-icon fa-solid fa-right-from-bracket"></i><p> Cerrar Sesión </p>
                    </a>
                </li>

            </ul>

        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>